name: Sync Providers Data

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch latest providers data
        run: |
          curl -s https://autumn-rain-b032.1021678642.workers.dev/providers > temp.json
          
          # 检查是否获取到有效的 JSON
          if jq empty temp.json 2>/dev/null; then
            # 比较版本号，只有当版本不同时才更新
            if ! cmp -s temp.json data/providers.json; then
              mv temp.json data/providers.json
              echo "Data updated"
            else
              echo "No updates needed"
            fi
          else
            echo "Invalid JSON received"
            exit 1
          fi
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/providers.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update providers data" && git push)
